name: Destroy EKS

on:
  workflow_dispatch:
  push:
    branches:
      - destroy  # This workflow will run when you push to this branch

      # Add this permissions block
permissions:
    id-token: write
    contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "arn:aws:iam::418272752575:role/github-actions-oidc-example20250511055154010500000001"
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - run: |
          cd ./stage/services/kubernetes-eks
          terraform init
          terraform destroy -auto-approve
