permissions:
  id-token: write
  contents: read 

name: Kubernetes EKS Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
      confirm_destroy:
        description: 'Type "destroy" to confirm destruction (only needed for destroy action)'
        required: false
  push:
    branches:
      - releases
    paths:
      - 'stage/services/kubernetes-eks/**'

jobs:
  terraform-action:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Increase timeout for EKS operations

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate destroy confirmation
        if: github.event.inputs.action == 'destroy' && github.event.inputs.confirm_destroy != 'destroy'
        run: |
          echo "Error: You must type 'destroy' in the confirm_destroy field to proceed with destruction"
          exit 1

      - name: Authenticate to AWS using OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "arn:aws:iam::418272752575:role/github-actions-oidc-example20250511055154010500000001"
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ./stage/services/kubernetes-eks
        run: terraform init

      - name: Terraform Apply
        if: github.event.inputs.action != 'destroy'
        working-directory: ./stage/services/kubernetes-eks
        run: terraform apply -auto-approve
        shell: bash

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        working-directory: ./stage/services/kubernetes-eks
        run: terraform destroy -auto-approve
        shell: bash
